---
title: "GNSS simulator"
---

An attempt to make a GNSS SDR simulator and use it for testing [balloon tracker payloads](https://github.com/anielsen001/high-altitude-balloon). This is based on an archived [LimeGPS simulator](https://github.com/osqzss/LimeGPS) since I have a LimeSDR. I built a podman container based on ubuntu 22.04 and installed the dependencies into it. Obtain the container by building:
```bash
podman-compose -f compose.yml build limegps
```
or pull the container
```bash
podman pull ghcr.io/anielsen001/gnss-sim:latest
```
and run it
```bash
podman-compose -f compose.yml run limegps
```
you can likely substitute `docker` for `podman`. 

## USB device access {#sec-usb-dev-access}

With podman you need to set udev access to the usb devices for your user. On my host system I have ubuntu 24.04 which does not currently (30 Nov 2025) have a `limesuite-udev` pacakge on the myriadrf ppa. However [myriadrf/LimeSuite github](https://github.com/myriadrf/LimeSuite/blob/master/udev-rules/64-limesuite.rules) has a set of udev rules that you can use to create the udev rules for the LimeSDR.

Copy this set of rules into `/dev/udev/rules.d/64-limesuite.rules`.

```
SUBSYSTEM=="usb", ATTR{idVendor}=="04b4", ATTR{idProduct}=="8613", SYMLINK+="stream-%k", MODE="666"
SUBSYSTEM=="usb", ATTR{idVendor}=="04b4", ATTR{idProduct}=="00f1", SYMLINK+="stream-%k", MODE="666"
SUBSYSTEM=="usb", ATTR{idVendor}=="0403", ATTR{idProduct}=="601f", SYMLINK+="stream-%k", MODE="666"
SUBSYSTEM=="usb", ATTR{idVendor}=="1d50", ATTR{idProduct}=="6108", SYMLINK+="stream-%k", MODE="666"
SUBSYSTEM=="xillybus", MODE="666"

SUBSYSTEM=="tty", ATTRS{idVendor}=="0403", ATTRS{idProduct}=="6001", MODE="0666"
```

Reload the udev rules with

```bash
sudo udevadm control --reload-rules
sudo udevadm trigger
```

## Running simulation

start the container
```bash
podman-compose -f compose.yml run limegps
```
you will drop to a shell prompt in the container. Run the simulator
```bash
/opt/LimeGPS -e brdc0350.18n -l 35.274,137.014,100
```

LimeSDR Mine output power is 10 mW.

## Reference projects

- [GPS SDR Sim, archived project](https://github.com/osqzss/gps-sdr-sim)
  - [anielsen001 fork](https://github.com/anielsen001/gps-sdr-sim)
  - [LimeSDR video spoofing a phone](https://www.youtube.com/watch?v=fAaiNOZmM20)
- [LimeGPS, LimeSDR version of GPS SDR sim, also archived](https://github.com/osqzss/LimeGPS)
  - [anielsen001 fork](https://github.com/anielsen001/LimeGPS)
- [Pokemon implementation of GPS SDR Sim](https://github.com/JiaoXianjun/poke-move)
  - [anielsen001 fork](https://github.com/anielsen001/poke-move)
- [Multi SDR GPS Sim](https://github.com/Mictronics/multi-sdr-gps-sim)
	- cites [hrfGPS](https://github.com/IvanKor/hrfGPS) by Ivan Kor 
- [GNSS SDR](https://gnss-sdr.org/)
  - this is a receiver only
- [GNSS SDRlib](https://github.com/taroz/GNSS-SDRLIB)

